// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACsKqHamEOe-rrSyY9Xzm1L3VKnXE-4p8',
    appId: '1:325635237345:web:1403b82fb7f8ec7c04dea0',
    messagingSenderId: '325635237345',
    projectId: 'mynewsapp-fdb92',
    authDomain: 'mynewsapp-fdb92.firebaseapp.com',
    storageBucket: 'mynewsapp-fdb92.appspot.com',
    measurementId: 'G-8Z1FSZ5MYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzmbUI-4pG6ZBR9-1bjFfSG40PeOso50',
    appId: '1:325635237345:android:d9285413387e222904dea0',
    messagingSenderId: '325635237345',
    projectId: 'mynewsapp-fdb92',
    storageBucket: 'mynewsapp-fdb92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEpU4zXCEjRhSN6sazACwrvCQZYNTLUQ',
    appId: '1:325635237345:ios:0e55174fb4dbf39004dea0',
    messagingSenderId: '325635237345',
    projectId: 'mynewsapp-fdb92',
    storageBucket: 'mynewsapp-fdb92.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEpU4zXCEjRhSN6sazACwrvCQZYNTLUQ',
    appId: '1:325635237345:ios:3cebd48637b076df04dea0',
    messagingSenderId: '325635237345',
    projectId: 'mynewsapp-fdb92',
    storageBucket: 'mynewsapp-fdb92.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
